[project]
name = "tms-shortener"
version = "0.1.0"
description = "A lightweight and extensible URL shortening service built with Django"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.4",
    "django-environ>=0.12.0",
    "gunicorn>=23.0.0",
]
